members/urls.py
from django.urls import path 
from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout_view, name='logout'),
]

notee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notesList.urls')),
    path('members/', include('members.urls'))
]

notesList/urls.py
from django.urls import path 
from . import views

app_name = 'notesList'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('notes/', views.NotesView.as_view(), name='notes'),
    path('update', views.UpdateView.as_view(), name='update'),
    path('delete', views.DeleteView.as_view(),name='delete'),
]

members/models.py
from django.db import models

# Create your models here.

notesList/models.py
from django.db import models
from django.contrib.auth.models import User

class note(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    notes = models.TextField()
    last_modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

members/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import IntegrityError


class LoginView(TemplateView):
    template_name = 'members/login.html'
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('notesList:notes')
        else:
            messages.success(request,("Enter Valid Credentials"))
            return render(request, 'members/login.html', {})


class RegisterView(TemplateView):
    template_name = 'members/register.html'
    
    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confpassword = request.POST.get('confpassword')
        
        if password != confpassword:
            messages.error(request, "Passwords do not match.")
            return render(request, self.template_name)

        try:
            User.objects.create_user(username=username, email=email, password=password)
            
            messages.success(request,("Registration is succesful"))
            return redirect('members:login')
        except IntegrityError:
            messages.success(request,("User already Exists"))
            return render(request, self.template_name)


def logout_view(request):
    logout(request)
    return redirect('notesList:home')

notesList/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic import View, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import note
from datetime import datetime


class HomeView(TemplateView):
    template_name = 'notesList/home.html'

class NotesView(LoginRequiredMixin, TemplateView):
    login_url = 'members:login'
    template_name = 'notesList/note.html'
    
    def get_context_data(self):
        context = super().get_context_data()
        context["user"] = self.request.user.username
        context["symbol"] = self.request.user.username[:1]
        user = User.objects.get(username=self.request.user.username)
        context["notes"] = note.objects.filter(username=user)
        return context
    
    def post(self, request):
        title = request.POST.get('title')
        notes = request.POST.get('description')
        current_datetime = datetime.now()
        user = User.objects.get(username=request.user.username)
        note.objects.create(username=user, title=title, notes=notes, last_modified = current_datetime)
        return redirect('notesList:notes')
    
class UpdateView(TemplateView):
    template_name = 'notesList/note.html'
    def post(self, request):
        title = request.POST.get('title')
        notes = request.POST.get('description')
        id = request.POST.get('uuid')
        current_datetime = datetime.now()
        note_data = note.objects.all().get(id=id)
        note_data.title = title 
        note_data.notes = notes
        note_data.last_modified = current_datetime
        note_data.save()
        return redirect('notesList:notes')
    
class DeleteView(TemplateView):
    template_name = 'notesList/note.html'
    def post(self, request):
        id = request.POST.get('uuid')
        note_data = note.objects.all().get(id=id)
        note_data.delete()
        return redirect('notesList:notes')

members/templates/members/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "members/css/login.css" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <div id="page">
        <div id="heading">
            <h1>NOTEE</h1>
        </div>
        {%if messages%}
            {%for message in messages%}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {%endfor%}
        {%endif%}
        <div id="login">

            <div id="block">
                <h3>Login</h3>
                <form action="{% url 'members:login'%}" method="POST">
                    {% csrf_token %}
                    <div id="blck">
                        <p>Login:</p>
                        <input type="text" name="username">
                        <p>Password:</p>
                        <input type="password" name="password">
                    </div>
                    <button id="log" type="submit">Login</button>
                </form>
                <button id="sign">
                     <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="LgbsSe-Bz112c"><g><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path><path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path><path fill="none" d="M0 0h48v48H0z"></path></g></svg> 
                     Sign in with google</button>
                <p id="rp">Doesn't have account? <a href="{% url 'members:register'%}" style="text-decoration: none;">Register</a></p>
            </div>

        </div>

    </div>
</body>
</html>

members/templates/members/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'members/css/register.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <div id="page">
        <div id="heading">
            <a href="./index.html" style="text-decoration: none;cursor: pointer;">
                <h1>NOTEE</h1>
            </a>
        </div>
        {%if messages%}
        {%for message in messages%}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {%endfor%}
        {%endif%}
        <div id="login">

            <div id="block">
                <h3>Register</h3>
                <form action="{% url 'members:register'%}" method="POST">
                    {%csrf_token%}
                    <div id="blck">
                        <!-- <p>Login:</p> --><br/>
                        <input type="text" name="username" placeholder="UserName">
                        <!-- <p>Email:</p> --><br/>
                        <input type="text" name="email"  placeholder="E-mail">
                        <!-- <p>Password:</p> --><br/>
                        <input type="password" name="password" placeholder="Password">
                        <!-- <p>Conforim Password:</p> --><br/>
                        <input type="password" name="confpassword" placeholder="Confirm Password">
                    </div>
                    <button id="log" type="submit">Register</button>
                </form>
                <button id="sign">
                     <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="LgbsSe-Bz112c"><g><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path><path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path><path fill="none" d="M0 0h48v48H0z"></path></g></svg> 
                     Sign in with google</button>
                <p id="rp">Already a user? <a href="{% url 'members:login'%}" style="text-decoration: none;">Login</a></p>
            </div>

        </div>

    </div>
</body>
</html>

notesList/templates/notesList/note.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Notee</title>
  <link rel="stylesheet" href="{%static 'notesList/css/note.css'%}">
  {% comment %} <script src="{% static 'notesList/js/note.js'%}"></script> {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <div id="main">

    <div id="navbar">
      <nav id="nav">
        <div id="circle">
          <h1 id="logo">{{symbol}}</h1>
        </div>
        <input type="text" id="searchInput" placeholder="search notes">
      </nav>
      <button id="logout"><a href="{% url 'members:logout'%}">LogOut</a></button>
    </div>

    <div id="name">
      <h2>Hey,<span>{{user}}</span></h2>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add Button
      </button>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <form method="post" action="{% url 'notesList:notes' %}">  
            {% csrf_token %}
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">ADD NOTE</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <input type="text" name="title" id="title" size="58" placeholder="Enter Title" required
                class=" mx-auto py-1 mb-3 px-2 text-xl  border-0 active:border-1">
              <textarea rows="4" cols="61" name="description" id="description" placeholder="Enter The Description"
                class=" mx-auto py-1 px-2 text-lg-start  border-0 active:border-1"></textarea>
            </div>
            <div class="modal-footer flex justify-content-start ">
              <button type="submit" class="btn btn-success">Save</button>
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    

    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <form method="post" action="{% url 'notesList:update' %}">  
            {%csrf_token%}
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">DATE</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <input type="text" name="title" id="title_show" size="58" placeholder="Enter Title" required
                class=" mx-auto py-1 mb-3 px-2 text-xl  border-0 active:border-1">
              <textarea rows="4" cols="61" name="description" id="description_show" placeholder="Enter The Description"
                class=" mx-auto py-1 px-2 text-lg-start  border-0 active:border-1"></textarea>
              <input type="hidden" name="uuid" id="uuid" />
            </div>
            <div class="modal-footer flex justify-content-start ">
              <button type="submit" class="btn btn-success">Update</button>
              <button type="submit" class="btn btn-danger" formaction="{% url 'notesList:delete' %}">Delete</button>
            </div>

          </form>
        </div>
      </div>
    </div>
    

    <div id="b1" style="display: flex;  flex-wrap: wrap;align-items: center; justify-content: center; ">
      {%for note in notes%}
        <button type="button" class="note-btn" data-bs-toggle="modal" class="border-0 " data-bs-target="#exampleModal1">
          <div class="card1">
            <p class="card-title">{{note.title}}</p>
            <p class="card-des"> {{note.notes}} </p>
            <p class="card-id" style="display:none"> {{note.id}} </p>
            <p class="card-text">
              <span>View More</span>
              <svg class="arrow-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16"
                height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z">
                </path>
              </svg>
            </p>
          </div>
        </button>
      {%endfor%}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

  <script>
    let elements = document.getElementsByClassName("note-btn");
  
    for (let element of elements) {
      element.onclick = function () {
        let title = this.querySelector(".card-title").innerText;
        let description = this.querySelector(".card-des").innerText;
        let id = this.querySelector(".card-id").innerText;
  
        document.getElementById("title_show").value = title;
        document.getElementById("description_show").value = description;
        document.getElementById("uuid").value = id;
      };
    }
  </script>

  <script>
  // Function to perform the search and highlight matching text
  function searchAndHighlight() {
    const searchInput = document.getElementById('searchInput');
    const keyword = searchInput.value.trim().toLowerCase(); // Trim and convert to lowercase for case-insensitive search
    const notesContainer = document.getElementById('b1');
    const notes = notesContainer.getElementsByClassName('note-btn');

    // Remove previous highlights
    removeHighlights(notesContainer);

    // Iterate through each note and highlight matching text
    Array.from(notes).forEach(note => {
      const titleElement = note.querySelector('.card-title');
      const descriptionElement = note.querySelector('.card-des');

      // Highlight matching text
      highlightText(titleElement, keyword);
      highlightText(descriptionElement, keyword);
    });
  }

  // Function to highlight matching text within an element
  function highlightText(element, keyword) {
    const regex = new RegExp(`(${keyword})`, 'gi');
    const text = element.innerText;

    if (regex.test(text)) {
      const newNode = document.createElement('span');
      newNode.className = 'highlight';
      newNode.innerHTML = text.replace(regex, match => `<span class="highlight">${match}</span>`);
      
      element.innerHTML = '';
      element.appendChild(newNode);
    }
  }

  // Function to remove previous highlights
  function removeHighlights(container) {
    const highlights = container.querySelectorAll('.highlight');
    highlights.forEach(highlight => {
      const parent = highlight.parentNode;
      parent.replaceChild(document.createTextNode(highlight.textContent), highlight);
    });
  }

  // Event listener to trigger search on input change
  document.getElementById('searchInput').addEventListener('input', searchAndHighlight);
</script>

  
</body>

</html>


<!-- box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px; -->